
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/BoxLinker/boxlinker-api"
  version = "0.1.0-dev1"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/cabernety/gopkg"

[[constraint]]
  name = "github.com/codegangsta/negroni"
  version = "0.3.0"

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "0.2.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  name = "github.com/docker/distribution"
  version = "2.6.2"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/docker/libcompose"
  version = "0.4.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/russross/meddler"

[[constraint]]
  branch = "master"
  name = "github.com/tevino/abool"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"
